server:
  port: 8080
  compression:
    enabled: true
    # 响应内容长度(Content-Length)进行压缩, 默认值为 2048 (2KB,不带单位时默认为字节)
    min-response-size: 10KB
    # 对指定的响应类型进行压缩, 逗号隔开
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml

spring:
  main:
    allow-circular-references: true
  application:
    name: gray-demo
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      # mvc 接收参数时对日期进行格式化
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sql:
    init:
      mode: always
      platform: mysql