bingo:
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ helper ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  helper:
    enables: caffeine,tracker,dynamic_db,alidns
  tracker:
    enables: spring,annotation,async,mysql,feign
    collector:
      enabled: true # 关闭收集器
      max-cache: 5
      rate: 1000
    repository:
      type: disk # 关闭存储
      disk:
        use-pid: true
        log-dir: /logs/tracker
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ dynamic datasource ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  db:
    default:
      name: spug
    blossom:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.31.66:3306/blossom?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
      username: root
      password: 'Root@123456'
    spug:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.31.66:3306/spug?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
      username: root
      password: 'Root@123456'
  mapping:
    db:
      blossom: blossom
      spug: spug
  slow-sql:
    blossom: '1'
    spug: '1'
  alidns:
    domain: javer.love
    accessKey: LTAI5tBsoTFmJfEGk4V7iaPU
    secretKey: 22NQRyPUXI0PO0wND6CypGhk0lF8Lv
    records: '@,www'
    ipv6: close